@extends('layouts.admin')
@section('title', 'Laporan Barang yang Sering Dipinjam - SINFAS')
@section('page_title', 'Barang yang Sering Dipinjam')
@section('styles') @include('admin.laporan.partials.styles') @endsection
@section('content')
@include('admin.laporan.partials.document-header', ['documentNumber' => '01', 'documentTitle' => 'Laporan Barang yang Sering Dipinjam', 'documentDescription' => 'Rekap jumlah peminjaman barang berdasarkan periode dan kategori yang dipilih.'])
@include('admin.laporan.partials.actions', ['pdfRoute' => 'admin.laporan.frekuensi.pdf'])
<div class="report-card formal-report"><div class="report-card-header"><div class="report-index">01</div><div><div class="report-card-title">Rincian Peminjaman</div><p class="report-card-description">Daftar barang beserta jumlah peminjamannya pada periode laporan.</p></div></div>@include('admin.laporan.partials.filter', ['reportRoute' => 'admin.laporan.frekuensi'])<div class="report-summary"><div class="summary-box"><div class="summary-label">Total transaksi</div><div class="summary-value">{{ $totalPeminjaman }}</div></div><div class="summary-box"><div class="summary-label">Jenis barang</div><div class="summary-value">{{ $totalBarangDipinjam }}</div></div></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>No.</th><th>Nama Barang</th><th>Kategori</th><th>Jumlah Dipinjam</th></tr></thead><tbody>@forelse($frekuensiBarang as $index => $item)<tr><td>{{ $index + 1 }}</td><td><strong>{{ $item['nama_barang'] }}</strong></td><td>{{ $item['kategori'] }}</td><td>{{ $item['frekuensi'] }} kali</td></tr>@empty<tr><td colspan="4" class="empty-report">Tidak terdapat data pada periode dan kategori yang dipilih.</td></tr>@endforelse</tbody></table></div><div class="trend-title">Grafik Peminjaman Harian</div><div class="trend-chart"><canvas id="trendPeminjamanChart"></canvas></div></div>
@endsection
@section('scripts')<script>new Chart(document.getElementById('trendPeminjamanChart'),{type:'line',data:{labels:@json($trenHarian->keys()->values()),datasets:[{label:'Peminjaman',data:@json($trenHarian->values()->values()),borderColor:'#287271',backgroundColor:'rgba(40,114,113,.12)',fill:true,tension:.3,pointRadius:3}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});</script>@endsection
