@extends('layouts.admin')
@section('title', 'Laporan Barang Terlambat Dikembalikan - SINFAS')
@section('page_title', 'Barang yang Terlambat Dikembalikan')
@section('styles') @include('admin.laporan.partials.styles') @endsection
@section('content')
@include('admin.laporan.partials.document-header', ['documentNumber' => '03', 'documentTitle' => 'Laporan Keterlambatan Pengembalian', 'documentDescription' => 'Daftar peminjaman yang melewati tanggal pengembalian yang telah ditentukan.'])
@include('admin.laporan.partials.actions', ['pdfRoute' => 'admin.laporan.keterlambatan.pdf'])
<div class="report-card formal-report"><div class="report-card-header"><div class="report-index">03</div><div><div class="report-card-title">Rincian Pengembalian Terlambat</div><p class="report-card-description">Termasuk barang yang belum dikembalikan dan pengembalian yang melewati batas waktu.</p></div></div>@include('admin.laporan.partials.filter', ['reportRoute' => 'admin.laporan.keterlambatan'])<div class="report-summary"><div class="summary-box"><div class="summary-label">Jumlah keterlambatan</div><div class="summary-value">{{ $keterlambatan->count() }}</div></div></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>No.</th><th>Nama Peminjam</th><th>Nama Barang</th><th>Tanggal Rencana</th><th>Keterangan</th></tr></thead><tbody>@forelse($keterlambatan as $index => $item)@php $sudahKembali = (bool) $item->pengembalian; @endphp<tr><td>{{ $index + 1 }}</td><td>{{ $item->siswa->nama ?? $item->nis }}</td><td>{{ $item->barang->nama_barang ?? '-' }}</td><td>{{ $item->tanggal_kembali?->format('d/m/Y') }}</td><td>{{ $sudahKembali ? 'Dikembalikan ' . $item->pengembalian->tanggal_kembali->format('d/m/Y') : 'Belum dikembalikan' }}</td></tr>@empty<tr><td colspan="5" class="empty-report">Tidak terdapat data pada periode dan kategori yang dipilih.</td></tr>@endforelse</tbody></table></div></div>
@endsection
