@extends('layouts.admin')
@section('title', 'Laporan Kondisi Barang - SINFAS')
@section('page_title', 'Kondisi Barang')
@section('styles') @include('admin.laporan.partials.styles') @endsection
@section('content')
@include('admin.laporan.partials.document-header', ['documentNumber' => '02', 'documentTitle' => 'Laporan Kondisi Barang', 'documentDescription' => 'Rekap kondisi barang berdasarkan laporan pengembalian yang telah tercatat.'])
@include('admin.laporan.partials.actions', ['pdfRoute' => 'admin.laporan.kondisi.pdf'])
<div class="report-card formal-report"><div class="report-card-header"><div class="report-index">02</div><div><div class="report-card-title">Rincian Kondisi Barang</div><p class="report-card-description">Jumlah kondisi baik, kurang baik, dan rusak berat pada periode laporan.</p></div></div>@include('admin.laporan.partials.filter', ['reportRoute' => 'admin.laporan.kondisi'])<div class="report-summary"><div class="summary-box"><div class="summary-label">Kondisi baik</div><div class="summary-value">{{ $kondisiRingkasan['Baik'] ?? 0 }}</div></div><div class="summary-box"><div class="summary-label">Kurang baik</div><div class="summary-value">{{ $kondisiRingkasan['Kurang Baik'] ?? 0 }}</div></div><div class="summary-box"><div class="summary-label">Rusak berat</div><div class="summary-value">{{ $kondisiRingkasan['Rusak Berat'] ?? 0 }}</div></div></div><div class="report-table-wrap"><table class="report-table"><thead><tr><th>No.</th><th>Tanggal Peminjaman</th><th>Nama Barang</th><th>Tanggal Pengembalian</th><th>Kondisi Barang</th></tr></thead><tbody>@forelse($riwayatKondisi as $index => $item)<tr><td>{{ $index + 1 }}</td><td>{{ $item->tanggal_pinjam?->format('d/m/Y') }}</td><td><strong>{{ $item->barang->nama_barang ?? '-' }}</strong></td><td>{{ $item->pengembalian->tanggal_kembali?->format('d/m/Y') }}</td><td>{{ $item->pengembalian->kondisi_barang ?? 'Belum dicatat' }}</td></tr>@empty<tr><td colspan="5" class="empty-report">Tidak terdapat data pada periode dan kategori yang dipilih.</td></tr>@endforelse</tbody></table></div></div>
@endsection
